import Head from "next/head";
import DisplayList from "../components/DisplayList";
import Toggle from "../components/Toggle";

import { useSession, signIn, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      {/* Head is a Next.js Component
      It's a wrapper around the native <head /> tag
      note: only put a Head component into _app if you want
      those properties to consist throughout every page */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!session && (
        <button onClick={() => signIn()}>Sign in with Google!</button>
      )}
      {session && (
        <button onClick={() => signOut()}>Sign out {session.user.name}.</button>
      )}

      <DisplayList
        listData={[
          { id: 1, data: "sZIA kIKI" },
          { id: 2, data: "I am data with id 2" },
        ]}
      />
      <Toggle />
    </>
  );
}
